# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: mkdmy

before:
  hooks:
    - go test ./...

builds:
  - id: mkdmy
    main: ./cmd/mkdmy
    binary: mkdmy
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: archives
    ids:
      - mkdmy
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  sort: asc
